### PR TITLE
Fixing issue #152: add colors in the slowest nodes page

### LINKED ISSUE #152: Add some colors in the slowest nodes page
Do the same way as the timeline (+legend)

### PR DESCRIPTION
**Pull request by TimotheeVrg**
# Issue Number:

Closes #152 
_The issue will be automatically closed if merged_

# Description:

Add components in the slowest nodes page
Add a colored legend and colors in the table

# How to test:

Launch the app `yarn dev`
Add a query plan
Go to the “Nodes” page
See the colors in the table (try changing the sorting in the different columns)

### CODE REVIEW

File: lib/types/index.ts [hunk 1]
```diff
@@ -36,3 +36,8 @@ export type Summary = {
   databaseRetrievalsExecutionContextElapsedTimings: Record<string, number>;
   retrievalsTypeCounts: Record<string, number>;
 };
+
+export const NODES_MAX_GREEN: number = 175;
```
Comment (tibo-mllr) [inline lib/types/index.ts:40]: Maybe you can use the same as for the Timeline? I don't remember their names but if you want you can rename them/change the export place

**Review by tibo-mllr — CHANGES_REQUESTED** [review]

File: lib/types/index.ts (hunk 1 above)
Comment (TimotheeVrg) [reply lib/types/index.ts:40]: Yes you're right, there must be some refacto since I re-used some elements (or slightly modified) for the timeline legend.
For sure I will change this const as you said
