### PR TITLE
Fix issue #67: improve slowest nodes page

### LINKED ISSUE #67: Improve slowest nodes page
- Add details in the table (mean, stddev,...)
- Choose how to sort
- Add colors in the lines
- Add the possibility to click on a line to have some details

### PR DESCRIPTION
**Pull request by TimotheeVrg**
# Issue Number: #67 

Closes #67 
_The issue will be automatically closed if merged_

# Description:
Improve the slowestNodes page. 
New information were added : average, stddev, parallelCount
You can sort the different columns
You can click on a row to see a dialog

# How to test:

After giving a query plan, go on "Nodes" page
Try to change the number of nodes
Try to sort the different columns
Try to click on different rows to the a dialog

### CODE REVIEW

**Comment by AlexandreCGithub** [comment]
For me it's ok but I'd like @tibo-mllr approve too since there is a lot of code

File: app/nodes/page.tsx [hunk 1]
```diff
@@ -33,11 +60,33 @@ export default function NodesPage(): ReactElement {
 
   const { aggregateRetrievals, databaseRetrievals } = queryPlan[selectedIndex];
 
-  const slowestNodes = getSlowestNodes(
-    aggregateRetrievals,
-    databaseRetrievals,
-    numberOfNodes,
-  );
+  const handleSort = (column: keyof ProcessedNode): void => {
+    const isAsc = sortColumn === column && sortOrder === "asc";
```
Comment (tibo-mllr) [inline app/nodes/page.tsx:64]: question: I believe it has a meaning, but I don't understand the first part `sortColumn === column` if you check the column again later

File: app/nodes/page.tsx [hunk 2]
```diff
@@ -33,11 +60,33 @@ export default function NodesPage(): ReactElement {
...
+    const newOrder = isAsc ? "desc" : "asc";
+    setSortOrder(newOrder);
+    setSortColumn(column);
+
+    const sortedNodes = [...displayedNodes].sort((a, b) => {
+      if (a[column] < b[column]) return newOrder === "asc" ? -1 : 1;
```
Comment (tibo-mllr) [inline app/nodes/page.tsx:70]: Could you maybe always put -1 or 1 in the `newOrder` and `sortOrder`? If it makes sense

**Review by tibo-mllr — COMMENTED** [review]
While you're changing the exports, could I abuse of your kindness and ask you to
- Remove the timeline folder as now it only has on file inside (except the index)
- Add the RetrievalDialog export in the index of the components, and change the two imports `import RetrievalDialog from '@/components/RetrievalDialog` to `import { RetrievalDialog } from '@/components'` ?

:pleading_face:

File: app/nodes/page.tsx (hunk 2 above)
Comment (TimotheeVrg) [reply app/nodes/page.tsx:70]: I'm not sure I completely understood what you want. 

I used `"asc"` and `"desc"` because for the `TableSortLabel` you can only give those strings for the `direction`

File: app/nodes/page.tsx (hunk 1 above)
Comment (TimotheeVrg) [reply app/nodes/page.tsx:64]: I don't know what you mean by "if you check the column again later"

The part `sortColumn === column` is there to differentiate if you want to sort the current sorted column (in this case I want to change the order) or another column (in this case the order is `asc` by default, I decided to choose that)

File: app/nodes/page.tsx (hunk 2 above)
Comment (tibo-mllr) [reply app/nodes/page.tsx:70]: Ooh okay, then let it like this!

**Review by tibo-mllr — APPROVED** [review]

**Review by AlexandreCGithub — APPROVED** [review]
You can update branch and merge if the pipeline passes
