### PR TITLE
Fixing issue #61 : add possibility to upload file

### LINKED ISSUE #61: Add possibility to upload file (Low priority)
In the Query page, a user can load a query plan by:
- Running a query against a server
- Paste a query plan

It would be nice to be able to upload the file directly without opening it, and copy pasting the query plan.

This is low priority and more of a quality of life feature.

### PR DESCRIPTION
**Pull request by AlexandreCGithub**
# Issue Number: 61

Closes #61 
_The issue will be automatically closed if merged_

# Description:

User will be able to upload files instead of direct text for entering queries or query plans

# How to test:

Launch the app `yarn dev`

Go to the main page localhost:3000

Check that uploading files for adding queries or query plans works

### CODE REVIEW

**Comment by AlexandreCGithub** [comment]
We can't test the upload of a query plan file since the server is done, but I tested and it sends exactly the same data as in the regular way so it is supposed to work.

File: app/submit-query/page.tsx
Comment (tibo-mllr) [inline app/submit-query/page.tsx:1]: First, I think you over-complicated things by adding your RadioGroup.
Just delete that, and always display the option to upload a file.
It's more user-friendly, and easier for us devs too: no need of the `inputMethod` things anymore

Second, I don't think you need the `fileTextQueryPlan` thing, you can just do it in the `manualQueryPlan` thing if in QueryPlan mode, or in the `text` value if in Request mode.

We easily get lost in all the code, conditions and everything in this page, we can simplify some logic.

File: app/submit-query/page.tsx [hunk 1]
```diff
@@ -33,43 +39,83 @@ export default function SubmitQueryPage(): ReactElement {
...
-      setError("Invalid JSON format in query plan.");
+        dispatch(setQueryPlan(JSON.parse(manualQueryPlan)));
+      } catch {
+        setError("Invalid JSON format in query plan.");
+      }
+    } else {
+      try {
+        setError(null);
+        dispatch(setQueryPlan(""));
+        console.log(fileTextQueryPlan);
```
Comment (tibo-mllr) [inline app/submit-query/page.tsx:110]: console.log

**Review by tibo-mllr — CHANGES_REQUESTED** [review]

File: app/submit-query/page.tsx
Comment (AlexandreCGithub) [reply app/submit-query/page.tsx:1]: How would it be decided if there is text in the regular field and a file uploaded

Comment (AlexandreCGithub) [reply app/submit-query/page.tsx:1]: I agree with deleting fileTextQueryPlan

**Comment by AlexandreCGithub** [comment]
I was a bit pessimistic, but this seems to do the job ...

File: app/submit-query/page.tsx [hunk 2]
```diff
@@ -103,63 +102,94 @@ export default function SubmitQueryPage(): ReactElement {
...
+                        sx={{ width: "100%" }}
+                      />
+                      <div>
+                        <label htmlFor="file" style={{ marginBottom: "8px" }}>
+                          Or upload a .txt file:
+                        </label>
+                        <input
+                          type="file"
+                          id="file"
+                          accept=".txt"
```
Comment (carlrizk) [inline app/submit-query/page.tsx:153]: I didn't read the entire PR, but I noticed this line. Why a `.txt` and not a `.json` ?

File: app/submit-query/page.tsx
Comment (tibo-mllr) [inline app/submit-query/page.tsx:1]: For easier understanding, that goes with the FileUploader component, you could create two components, one for sending the request, one for directly giving the Query plan, and just switch between these two?
```
{!isManualMode ?
    <QuerySenderComponent />
    : <QueryPlanInpuComponent />
}
```

Or something like that?

**Review by tibo-mllr — CHANGES_REQUESTED** [review]

File: app/submit-query/page.tsx (hunk 2 above)
Comment (AlexandreCGithub) [reply app/submit-query/page.tsx:153]: Yes

File: app/submit-query/page.tsx [hunk 3]
```diff
@@ -170,6 +200,37 @@ export default function SubmitQueryPage(): ReactElement {
                 onChange={(e) => setManualQueryPlan(e.target.value)} // Update state
               />
 
+              <div>
+                <label htmlFor="file" style={{ marginBottom: "8px" }}>
+                  Upload a .txt file:
```
[the remark this answers is not in the document]
Comment (AlexandreCGithub) [reply app/submit-query/page.tsx]: Ok

File: app/submit-query/page.tsx [hunk 4]
```diff
@@ -103,63 +102,94 @@ export default function SubmitQueryPage(): ReactElement {
...
-                      type="submit"
-                      variant="contained"
-                      className="w-full"
-                    >
-                      Send and receive query plan
-                    </Button>
-                  </Form>
-                )}
+                {({ setFieldValue }) => {
+                  return (
```
[the remark this answers is not in the document]
Comment (tibo-mllr) [reply app/submit-query/page.tsx:107]: I can do it on my computer and it works fine, so maybe there's a thing done wrong indeed

**Review by tibo-mllr — APPROVED** [review]
