### PR TITLE
Fixing issue #198 : refactoring summary page

### LINKED ISSUE #198: Summary page : refactor some elements
There are opportunities for refactoring sections of the summary page, especially when we display the pie charts and we choose between grouped and non-grouped retrievals display

### PR DESCRIPTION
**Pull request by AlexandreCGithub**
# Issue Number: #198 

Closes #198
_The issue will be automatically closed if merged_
Contributes to #199 

# Description:

Refactoring summary page, adding components and avoiding repeats

# How to test:

Launch the app `yarn dev`
Load a query plan
Go to page: `summary`
Check that the page behaves exactly like main

### CODE REVIEW

File: app/summary/page.tsx [hunk 1]
```diff
@@ -142,23 +144,9 @@ export default function SummaryPage(): ReactElement {
...
-                          >
-                            {pieDataElapsedTimings.map((entry) => (
-                              <Cell key={entry.name} fill={entry.fill} />
-                            ))}
-                          </Pie>
-                        </PieChart>
-                      </ResponsiveContainer>
+                      <TimingPieChart
+                        data={pieDataElapsedTimings}
+                      ></TimingPieChart>
```
[the remark this answers is not in the document]
Comment (AlexandreCGithub) [reply app/summary/page.tsx]: You're right of course, I did forget this

File: app/summary/ui/SummarySection.tsx [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+  Tooltip,
+} from "@mui/material";
+
+interface SummarySectionProps {
+  title: string;
+  description: string;
+  data: string[] | Record<string, number>;
+}
+
+const SummarySection: React.FC<SummarySectionProps> = ({
```
Comment (tibo-mllr) [inline app/summary/ui/SummarySection.tsx:19]:
```export default function SummarySetion({
  title,
  description,
  data,
} : SummarySectionProps {...```

As we do for every component we have in the app

File: app/summary/ui/TimingList.tsx [hunk 3]
```diff
@@ -0,0 +1,31 @@
+import { Box, List, ListItem, ListItemText } from "@mui/material";
+import React from "react";
+
+interface TimingListProps {
+  data: Record<string, number>;
+  colorMap?: Record<string, string>; // color not mandatory
+}
+
+const TimingList: React.FC<TimingListProps> = ({ data, colorMap }) => {
```
Comment (tibo-mllr) [inline app/summary/ui/TimingList.tsx:9]: Same here

File: app/summary/ui/TimingPieChart.tsx [hunk 4]
```diff
@@ -0,0 +1,31 @@
+import { PiePartData } from "@/lib/types";
+import React from "react";
+import { ResponsiveContainer, PieChart, Pie, Cell } from "recharts";
+
+interface TimingPieChartProps {
+  data: PiePartData[];
+}
+
+const TimingPieChart: React.FC<TimingPieChartProps> = ({ data }) => {
```
Comment (tibo-mllr) [inline app/summary/ui/TimingPieChart.tsx:9]: Same here

File: app/summary/page.tsx [hunk 5]
```diff
@@ -26,7 +26,9 @@ import {
 
 import { ReactElement, useMemo, useState } from "react";
 import { useSelector } from "react-redux";
-import { PieChart, Pie, Cell, ResponsiveContainer } from "recharts";
+import SummarySection from "./ui/SummarySection";
```
Comment (tibo-mllr) [inline app/summary/page.tsx:29]: What is `SummarySection` supposed to mean in a Summary?

**Review by tibo-mllr — CHANGES_REQUESTED** [review]

File: app/summary/page.tsx (hunk 5 above)
Comment (AlexandreCGithub) [reply app/summary/page.tsx:29]: a section of the summary

**Review by tibo-mllr — APPROVED** [review]
